### ISSUE TITLE
App aborts if received a server error

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#108]
#### Description
**Is**:
1. Request with a failure response like 500.
2.  Web ui displays error
3. Close popup, but client is stucked, user needs to reload the app.

**Should**:
App should operate normally after such responses.

#### balloon web client version
v3.0.7

**Comment by raffis** [comment]
Not reproducible

**Comment by raffis** [comment]
I have this now if the server responds with error 500 from node?query=xy request. For example if error 500 while opening the menu "filtered nodes" in v3.0.10 dev

**Comment by pixtron** [comment]
```
Uncaught ReferenceError: response is not defined
    at Object.error (core.js?410f:8769)
```
