### ISSUE TITLE
Share search user/group input field looks different than expected

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#114]
#### Description
**Is**:
Search user/group input field looks different than expected. Maybe because of latest browser changes.
![selection_043](https://user-images.githubusercontent.com/2376735/50839121-eec1a600-135f-11e9-8901-4ff1449593fd.png)

**Should**:
Input should have the same width as the input field above.

#### balloon web client version
v3.0.8

#### Your client operating system
Linux Mint 17

#### Your browser
Firefox 61

**Comment by pixtron** [comment]
@raffis i successfully testet this on FF 61,62 and 64 and Chrome 71 on OSX and could not reproduce the issue on current dev branch and v3.0.1 ... v3.0.8. Although i can reproduce it on the live server.
