### ISSUE TITLE
Possibility to change password from local db auth adapter

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#116]
#### Description
**Is**:
Currently there is no way for the user to change the internal balloon password via the web ui.

**Should**:
Add "Change password" possibility.
This must only be visible if authenticated via basic auth.

PATCH to /api/v2/users/{my_user_id} - {password: "new pass"}

**Comment by pixtron** [comment]
- only if user is logged in with basic auth
- request : patch /api/v2/users/:userId {password: 'newpass'}
- old password should be entered and used for the request (if possible)

**Comment by raffis** [comment]
@pixtron See issue #141 and the server v2.5 also provides a new attribute called "auth". The password change mechanism must only be visible if auth==="internal"
