### ISSUE TITLE
Copy and move should resend request with conflict=2 if Conflict 19

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#118]
#### Description
**Is**:
1. Create folder /a
2. Create /folder/b
3. Create file /b/a
4. Move or copy /b/a to /a
5. Exception\Conflict error code 19

**Should**:
If response is Exception\Conflict error code 19, the app needs to ask if nodes should get merged and resend the request with conflict=2
(Like undelete already does, it's basically the same).

#### balloon web client version
v3.0.9

**Comment by pixtron** [comment]
This issue is still open for multi node requests, but this will be handled in #125.
