### ISSUE TITLE
Loader not visible during long running search requests

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#119]
#### Description
**Is**:
1. Search query (text)
2. Request takes a while
3. I can't see a loader, looks like nothing is happening

**Should**:

#### balloon web client version
v3.0.9

**Comment by raffis** [comment]
May also be fixed in a branch for #129

**Comment by pixtron** [comment]
@raffis is this still an issue? In v3.2.x branch the spinner on top of the page is shown.

**Comment by raffis** [comment]
@pixtron This is still a bug in v3.2.x. And has been reported back in 2017 ( #5) as well.
This may happen if the server response takes a while (Slow running search requests).

**Comment by pixtron** [comment]
Reproducible when search query is typed "fast", letter by letter the loader is displayed.
