### ISSUE TITLE
NTH: Own app for elastic search

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-web#129]
#### Description
**Is**:
All search functionality is in core.

**Should**:
Create an app "eleastic search" contianing 

a.) Fulltextsearch, filtered search, click on tags in right side 
b.) Fulltextsearch only (would require to have filtered queries in core as mongo queries and additionaly in app as elasticsearch queries)

Also see see #126

**Comment by raffis** [comment]
Also see #69
