### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by unvorhergesehen** [gyselroth/balloon-client-web#137]
#### Description
**Is**

**Should**:
* markdown will be parsed nicely
* markdown can be edited online

**Comment by raffis** [comment]
nice feature request :+1:

**Comment by raffis** [comment]
https://github.com/showdownjs/showdown

**Comment by raffis** [comment]
stuff to do:

* Parse file and display first with edit button if content exists, if not display markdown editor directly
* easy linking and browing between md files on balloon. Meaning if click on a link the md display popup should load the linked page

Separate issue (Advanced markdown):
* loading images from balloon (And uploading them by drag & drop)
