### ISSUE TITLE
Support for two factor auth and token authentication

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#141]
#### Description
**Is**:
Upcoming balloon v2.5.x has an integrated Idp and supports two factor auth via google authenticator, see https://github.com/gyselroth/balloon/issues/242 and https://github.com/gyselroth/balloon/issues/285

**Should**:
Integrate support for oauth flows password and password_mfa grant flows. Add new config: credentials which can either be null (no credentials login), "token" (oauth2 first party authentication) or "basic" (HTTP basic authentication).

**Note**: If authenticated via token (which will be the default), its also possible to verify a password during a password change (Which is not possible with basic auth).

Todos: 
1. Implement auth via token auth POST /api/v2/tokens (first party auth grant types)
2. Add input for token if grant_type password_mfa
3. Add user profile setting to enable two factor auth (send a PATCH to /api/v2/users/{id}) multi_factor_auth: true. **IMPORTANT** the server will respond with a field: multi_factor_uri which will hold the OTP url to generate a qr code and display it to the user but only this time!
This field wont be accessible after. Once activated two factor auth there is no way to get this url again.
The two factor auth must only be visible if the user is not logged in via an external oidc provider.

#### balloon web client version
v3.0.9

**Comment by raffis** [comment]
note changes made in branch issue-141 require balloon server v2.5.x for token auth, else set config credentials to `basic`.

**Comment by pixtron** [comment]
change password should also be in profile window

**Comment by pixtron** [comment]
user.auth attribute only visible for whoami,

- 2FA not possible if user.auth === external &&  oidc authentication
- Change password only possible for user.auth === internal

**Comment by raffis** [comment]
@pixtron "2FA not possible if user.auth === external && oidc authentication"

2FA should be visible if user.auth === external && oidc authentication internally. Meaning if the token idp is the balloon server, two factor auth should be visible, even if user.auth === external.
