### ISSUE TITLE
Search over Event Log

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-web#143]
#### Description
**Is**:
Events are not searchable
**Should**:
Text field, search $or[node.name, node.id, previous.name, (operation)]

**Comment by pixtron** [comment]
@raffis if i see it right, balloon server would need to implement queries for the event-log parameter before we can implement this issue?

https://github.com/gyselroth/balloon/blob/82cdd15362b3f0adc255b784e7cce7aa4238c204/src/app/Balloon.App.Api/v2/Nodes.php#L403

**Comment by raffis** [comment]
> @raffis if i see it right, balloon server would need to implement queries for the event-log parameter before we can implement this issue?
> 
> https://github.com/gyselroth/balloon/blob/82cdd15362b3f0adc255b784e7cce7aa4238c204/src/app/Balloon.App.Api/v2/Nodes.php#L403

Yes, see https://github.com/gyselroth/balloon/issues/315

**Comment by raffis** [comment]
query (probably name and old name):
\{"$or":\[\{"name":"QUERY"\},\{"previous.name":"QUERY"\}\]\}

**Comment by raffis** [comment]
@pixtron implemented in server 2.6.0-alpha4

**Comment by raffis** [comment]
@pixtron some changes/fixes:
1. If you hit enter two times (fast), there will be two time a "no events found"
2. Remove the search input content should display all events, currently we get "no events found"
3. Can you change [{"name":"QUERY"},{"previous.name":"QUERY"}] to a regex query for both fields? ({"$regex":{}) (same as it is in use for file search)

**Comment by pixtron** [comment]
@raffis above changes are implemented.
