### ISSUE TITLE
browser not responding using ie11 after download

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#160]
#### Describe the bug
IE11 popup "balloon (url) not responding".

#### To Reproduce
1. Select node
2. Download node
3. Popup not responding, spa need to get reloaded

#### Environment
 - web-client version: v3.1.1
 - balloon server version: v2.5.2
 - Deployed as: docker
 - client os: Windows 10
 - browser: IE11

**Comment by pixtron** [comment]
I could not reproduce this issue on IE11/Win 10

**Comment by raffis** [comment]
browser vendor related issue. May happen but there is most certainly nothing we can do about it.
