### ISSUE TITLE
Clicking on a tag throws error

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-web#174]
#### Describe the bug
When clicking on a tag, an elastic search error is shown. 
```
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[bool] query malformed, no start_object after query name","line":1,"col":55}],"type":"parsing_exception","reason":"[bool] query malformed, no start_object after query name","line":1,"col":55},"status":400}
```
#### To Reproduce
1.) select a node
2.) add a tag
3.) click on added tag

#### Expected behavior
The query should work

#### Environment
 - web-client version: 3.1.2
 - balloon server version: 2.5.4
 - Deployed as: N/A
 - client os: N/A
 - browser: N/A

**Comment by pixtron** [comment]
Related to: #126

**Comment by pixtron** [comment]
Steps to reproduce in search_issues branch:

1.) Switch to fulltext search
2.) Open Filter
3.) Activate one or more filters
4.) Apply Filter

**Comment by pixtron** [comment]
After PR #189 has been merged the issue is only reproducible in `Balloon.App.Elasticsearch`

**Comment by raffis** [comment]
@pixtron this has been an issue in the latest balloon alpha, is fixed now.
