### ISSUE TITLE
Open a html file (~50kB) in balloon file editor

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#200]
#### Describe the bug
The browser gets stuck for around 15s.

#### To Reproduce
1. Upload ~500kB html file.
2. Open file with balloon file editor

#### Expected behavior
No such lag or the message that the file is too big must be prompted.

#### Environment
 - web-client version: v3.2-alpha
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: [e.g. Linux Mint 19.2]
 - browser: [e.g. Firefox 62]

**Comment by pixtron** [comment]
Could not reproduce the described problem. Although it was not possible to open more then one file after each other. Probably this made the impression, that it has to do with "big" files.
