### ISSUE TITLE
iOS PWA spashscreen logo balloon is spawned over the whole page

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#203]
#### Describe the bug
On iOS PWA the balloon logo is over the whole splashscreen.
Unlike android where the logo is smaller and centered.

#### Environment
 - web-client version: v3.2-beta
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: [e.g. Linux Mint 19.2]
 - browser: [e.g. Firefox 62]

**Comment by pixtron** [comment]
Fix requires expo/expo-cli/pull/667
