### ISSUE TITLE
Use icons from icon-collection

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-web#204]
#### Describe the change
The markdown editor should use the icons from gyselroth/icon-collection.
Check if additional icons  are necessary.

#### Current situation
Fontawesome icons are loaded from external cdn.
 
#### Should
Use custom icons

**Comment by pixtron** [comment]
Related to #137

**Comment by pixtron** [comment]
@raffis we need these additional icons: `heading-1`, `heading-2`, `heading-3`, `quote`

**Comment by raffis** [comment]
@pixtron published in v1.0.10
Can you also use the new fingerprint icon instead the current one?
