### ISSUE TITLE
open a file on iPad landscape does not work 

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon-client-web#211]
#### Describe the bug
On an iPad with Screen width >799px a touch on a node, does not open the file.
The only way to open a file is by clicking on the preview.

#### Environment
 - web-client version: 3.2.0-alpha3
 - balloon server version: NA
 - Deployed as: NA
 - client os: iOS 12.2
 - browser: pwa (safari)

**Comment by raffis** [comment]
Maybe a polyfill will work: https://gist.github.com/mckamey/2927073/92f041d72b0792fed544601916318bf221b09baf
