### ISSUE TITLE
Search input does not show up on mobile

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#213]
#### Describe the bug
Click on the search button does not bring up the search input.

#### To Reproduce
1. Click on search
2. No search input

#### Expected behavior
Search input (like it was in alpha5)

#### Environment
 - web-client version: v3.2.0-alpha6
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: Android
 - browser: Chrome (PWA)

**Comment by pixtron** [comment]
Closing the issue as it can't be reproduced.
