### ISSUE TITLE
Fast click multiple times on file will left the app with a .k-overlay and one need to reload the browser

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#246]
#### Describe the bug
If one clicks multiple times on a file (image, markdown, ..) quite fast it can be that one is left with only the grey area (.k-overlay) from the popup.
Browser reload is required. Since neither can this state be closed via click or esc.

#### To Reproduce
Fast click 4 times on the file.
(The pop will open and close during that time and after the 4th click the user is left with a .k-overlay)

#### Expected behavior
Should not happen, either a popup should be displayed or not but not a state between.

#### Environment
 - web-client version: v3.2.4
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: Linux Mint 
 - browser: Chrome

**Comment by pixtron** [comment]
This has to be tackled for all modals. When calling `$el.kendoBalloonWindow()` it needs to be checked first, if the same element has already a `kendoBalloonWindow` (`$el.data('kendoBalloonWindow') !== undefined`). If `$el` already has a `kendoBalloonWindow`, the existing one should be reused. This also requires, that all window initialization, is outside the `open` event.
