### ISSUE TITLE
Differences in closing fullscreen window with office

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#258]
#### Describe the bug
If an office fullscreen window gets started, it may be closed via close or ESC.
(Note with ESC issue #257 is also affected.)

If the windows gets closed via close, the popup closed immediately. If one clicks with the cursor on the right side of the window first (not in the iframe), and then hit esc, balloon asks if the file got already saved.

#### To Reproduce
See above.

#### Expected behavior
1. Always close if one hits [ESC] (#257 )
2. The same action if ESC or close button. 

Best: Check if the file got saved somehow or trigger save. Maybe this is possible via PostMessage: https://wopi.readthedocs.io/en/latest/scenarios/postmessage.html

#### Environment
 - web-client version: v3.2.6
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: Linux Mint
 - browser: Firefox

**Comment by pixtron** [comment]
As office itself is listening to `ESC` in some cases (eg. marked text), it does not make sense to listen on `ESC`to close the document, while the focus is in Office itself.
