### ISSUE TITLE
can't access to my balloon server

### ISSUE THREAD

**Issue by micdech** [gyselroth/balloon-client-web#259]
Hi all,
i've this problem with my fresh installed balloon server and web client.

Seems that i need a user name and password from .htpasswd but i don't know which are.

just tried with user and password provided by documentation admin / admin but nothing happens.

leave a screenshot to understand the problem.

Can anyone help me?

![balloon_screenshot](https://user-images.githubusercontent.com/1315671/61370209-27ec4d00-a892-11e9-8f19-85ff86b3007e.png)

**Comment by micdech** [comment]
in addition:

my server is ubuntu based 18.04. 
Balloon installation provided by documentation following Debian based distribution

**Comment by raffis** [comment]
> Hi all,
> i've this problem with my fresh installed balloon server and web client.
> 
> Seems that i need a user name and password from .htpasswd but i don't know which are.


There is no htpasswd. The balloon server comes with an integrated authentication system.
If admin/admin does not work, try to initialize the server (again):

``
ballooncli upgrade -i -vvv
```

This should create the admin account admin:admin.
If the authentication still does not work after this, please provide the server logs.

**Comment by micdech** [comment]
my mistake. sorry ;)
Now, the problem is on elasticsearch:

`[2019-07-17T12:52:53.982091+00:00] default.ERROR: can not create index, try to update existing index {"category":"Balloon\\App\\Elasticsearch\\Migration\\Delta\\Installation","exception":"[object] (Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException(code: 0): No alive nodes found in your cluster at /usr/share/balloon/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:53)"} []
[2019-07-17T12:52:53.982399+00:00] default.ERROR: failed to apply delta [Balloon\App\Elasticsearch\Migration\Delta\Installation] {"category":"Balloon\\Migration","exception":"[object] (Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException(code: 0): No alive nodes found in your cluster at /usr/share/balloon/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:53)"} []
`

Do i need to insert new issue for this?

**Comment by raffis** [comment]
Well balloon can't find your elasticsearch instance.
Did you deploy elasticsearch on your local machine or somewhere else?
Is elasticsearch running: `curl localhost:9200` ?
