### ISSUE TITLE
json query for users/groups is not properly escaped

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#260]
#### Describe the bug
Invalid json provided while searching for user/groups with an `&` character.

#### To Reproduce
1. Search for test&test in share resources (user/groups)
2. Server api exception: invalid json provided 

request: api/v2/users?{%22query%22:{%22username%22:%22test&test%22}}
`&` should be escaped.

#### Expected behavior
1. Instead ?json used ?query=json.
2. Properly urlencode query

#### Environment
 - web-client version: v3.2.6
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: [e.g. Linux Mint 19.2]
 - browser: [e.g. Firefox 62]

**Comment by danielkleeb** [comment]
fixed by 527ee75a6ecf883dc99e6b1d81a303cad25180fb
