### ISSUE TITLE
Web ui buggy with iPhone 10, scrolling and selection not working

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#267]
#### Describe the bug
The bug is visible here: https://photos.google.com/share/AF1QipNR4LbFLEq5q9A0uqyLgdpaHerQkn6vRXmhqEt_U6AJmYoRNYOXgJstu3ht7IQgMg?key=amx6am9XdXQxS2E2cW9pVExiWnFIS0tUaWpQQ2JB

and here:
https://photos.google.com/share/AF1QipPmwrqQoL7ltsZrDgjECrGyiWCezIMrrnM6PAFq_4UH9Q01bJpPB0xzPwsEix_Yjg?key=SWhSakZ4T3VLM2ROUm82aklxNkZpaWtVU1dWWFJB

Things which are not working:
* Scrolling is buggy
- Selection of multiple nodes
- Buttons, click on the side

#### To Reproduce
Reproducible with iPhone 7 and iPhone 10.
It works with iPhone 5.

#### Environment
 - web-client version: v3.2.7

**Comment by pixtron** [comment]
- The Scrolling issue has been introduced with iOS 13.
- Tap on a node during multiselect should not open App Handler.
