### ISSUE TITLE
APP-Download Icon not available

### ISSUE THREAD

**Issue by franz-ferdinand** [gyselroth/balloon-client-web#270]
Web  clien, Help, first item:
«Es gibt eine App, welche deine ganze Cloud auf deinen Desktop bringt. Die App gibt es für Windows, Mac OS X und Linux. Du kannst diese herunterladen, indem du auf <ICON> klickst unten links.»

You can't find an icon for download.

**Comment by raffis** [comment]
@franz-ferdinand There is no bug. The downoad for the desktop client probably has been disabled in your deployment of balloon.
