### ISSUE TITLE
After adding external storage the browser prompts to save the password after every request

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#76]
#### Description
**Is**:
1. Add external storage
2. Change folder or something else
3. The browser prompts to save the password

**Should**:
Browser must never aks to store a password for an external storage mount since this would not make any sense.

#### balloon web client version
v3.0.1

#### Your client operating system
Linux Mint 17

#### Your browser
Firefox 61

**Comment by raffis** [comment]
@pixtron is this still a thing?

**Comment by pixtron** [comment]
@raffis I could never reproduce this issue.

**Comment by pixtron** [comment]
Above commit solves the problem for chrome. Seems there is no other clean solution for other browsers, as most modern browsers do ignore the autocomplete="off" attribute.
