### ISSUE TITLE
Implement all features from the desktop version into the mobile version

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#81]
#### Description
**Is**:
One can only browse the cloud in the mobile version.

**Should**:
Select node => the whole right menu should be available in mobile.

**Comment by pixtron** [comment]
https://projects.invisionapp.com/share/Q3DQ7FB5Y#/screens/255937609

**Comment by raffis** [comment]
@pixtron todo v3.2.x:

* back button on the top left is too far away to easily navigate => additionally swipe right to go back
* remove refresh button on responsive screen (already done via pull down)
