### ISSUE TITLE
Support for progressive web app (pwa)

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#82]
#### Description
* Add manifest.json
* Add header icons for ios/windows
* Possibility to prompt for install (add to home screen)
* ServiceWorkers?

**Comment by raffis** [comment]
Would be awesome if we can securely store the refresh_token / access_token on the mobile device. The balloon server v2.5 is shipped with an internal Idp and provides both tokens via the user owner password grant. 

A plus would be if we can authenticate the user via the fingerprint sensor once the user was initially authenticated.

You do not want to authenticate yourself with username/password on a mobile app every time the app gets opened.

**Comment by raffis** [comment]
fingerprint auth my be possible with the [web auth api](https://www.w3.org/TR/webauthn/).

**Comment by raffis** [comment]
Nice (native) app feelings:

* easy authentication (for example store tokens encrypted with fingerprint)
* Share with app (balloon app should be visible as share target), should be implemented in chrome > v70
* menu swipe
* ...?

**Comment by pixtron** [comment]
Eventually we could use service workers for a "long living" session:  https://developers.google.com/web/updates/2016/06/2-cookie-handoff
