### ISSUE TITLE
Nice urls, easy way to share balloon url's

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#83]
#### Description
**Is**:
Currently the urls are only formatted using query strings.

**Should**:
Use url rewriting:

/nodes/id, /shared-links/id, ...

**Comment by raffis** [comment]
* There should also be an action button which allows to cop the current url automatically.
* This url should be exchangeable with internal balloon users

**Comment by pixtron** [comment]
also see #122
